//{ Driver Code Starts
// #include <bits/stdc++.h>
#include<iostream>
#include<string>
using namespace std;


// } Driver Code Ends
class Solution
{
    public:
    //Function is to check whether two strings are anagram of each other or not.
    bool isAnagram(string a, string b){
        
        // Your code here
        int ans = 0;
        for(int i = 0; a[i] != '\0' || b[i] != '\0'; i++){
            ans = ans ^ a[i] ^ b[i];
        }
        if(ans == 0)
            return 1;
        else
            return 0;
        
    }

};

//{ Driver Code Starts.

int main() {



        string c = "muapfxqbxgxbnyktgibeewjzjjtncnfuckxlaggbagozxmpjboblymhqvbfxcqlaitycparbatutksaitxhthebvdheibfvbijnqlzqwrhijrqepczdihogqavumlyuzwjufevpkuqakrowbtafuuzdthkefhdkgbabsrcxovtvlwfkeojoejseblvftenbddtcpbxwmrbdgfogqjnqsijxelmnmgtlhvndwxteyheopjzidueknqzslwgytewgwokhemkbfyxkutnsnspilkvdsudinmxssukytwkerbnxbsnphddbkrhnnebfakoellamjqzhkrwafebgwwbntirvnwlsadfuvsfrdigzxzpdbwnpahbqaesvusxvyajlpidlbbtlfdwvhmsdxptizgmcwftkucraaffuslsrjkkonpziurgdjlhyiajiucxpmdwqihaxdsithzdqdkvyvffxodulteoibpeyzsgblvkckppvsnplzfrfifjxeurxplrekyghjsdbhsvzkredzsbtnaekcxkcrecnxejepgyegrpdfhbcpbmfvtgbkdgosdivrklzifzwxnkfoxwlfrbmxgawbdhpezufqzvcovczcutojieskbfgrkefwqcvztjjcjkiztnmwnkdmvwsbqaqroxtmtcdlpnumxexbhyojayuirgxstaggknsahvvpquasokzrmkbvweljpxqbpreghhaiomtbkbmildkxtyldlgovyltuqthvjexirgzzxfsthhgbpfwcbdrzxxfctmeyncfckzamikllappspasomqfrxmaofzdihudzspizdhbijawdgbcbfznzpgtqbdrnydijdipkkrgzkyrspspymlboxedigvgbvfskabojzgsyasjfatzblxecuphiansizqghisnihnbybspnwzdwvhmizvcusevknvibwnejgvybujxipdbtqvzgxzcfyyzcgbgmbdjuxauvmafsvafhpwfstiusxmoltnskvduzgnrnptsdzaxdvzcfbiehrpovykokzvoaynypkrnwmbfufvffsiuwvzhauguygvwnekncvfeqgekfyqqpasoqonbqirecvmoatckczlknjqkxamwdkzytndvyhorupbligadbwnplyvktajsnoumxbejbeohhnzfehtiyhwdsvslylvmazpotyfhxmvgkonyydctllrazfsvpqaigexanfgjamuwhdraweprifbovjmwelyepakeadqtmcgzgrnbdfvkmevjmgkopuxsewrdkvinkjhdhsujfkhdxcvrqhwllprfrabtziitrzeunzdxugxphoftbnhmycpwifmmsfrmaugldxrnnsgcdcgjgdssmcuzynbudpjakflufzkuqswabdbaxhydchzrbwrjsnnrcxwotamfzztairwxsgrkjeomgjkxmoktjabvzzjoffmfwdyamhcbhnimzjxuummcwypgtvrzexjbbqmddlfspkrlimprgymykkhtugimpxgpyuagilhnqgllwkucifvvnmjinpcfgcplfkftfkrsvyufhgrjmixfxpcmwsblbdpzbwqfgvhskslzidcykamfyrqdttbwnhztilngchehecoufjklrucxtiashppsgjsbcrmcdbyezxrxmrcgotjizlbegxmpwsubsfohudsmdbhegwmpfoxfqdtdyhptcxxjuiizjoblztffpvnuakemekrdqlsidumjwvdiultnbczulttihtondsmcwotwaymijlyuofvmnzwdbiplzezncgcershdysrmlctllvackzzhhkogxghkxqgfxmdfelcbqnghdmqtmdyzfycqxaozytvzcsfwfgwhxcmtxnodpkhrmwcfhdcmeyfhvomvaozqkcctyitxqqhitdhxtdssoybtyelaagigohegnobrbevywmzpnjjbqwunnctdtyoxdalfvketxrgvzapailezmeyvftgklfnazeynjjrpwgbfegcuzglmvlbjiiilmcqpjxthisxnkiyabrgoeesgzncrssodxqkztezlxithuuvlmgjwnuyqmvmtehpprqpeevjkvyxtkdjydhiydzkeoryrkokjkplvabryopjigsxihdkgosivmmwubchomkrcvmrcqknkpmjkbfuauibwbbssswhgtqgqmhoyjfyaixewiqvyehejdpqagdavlahnbptvunshpqhukhjoygrgazgbjtpzxoiiyjtrlzvruykujjunfwpfkxwxczpagjflkmjnoecifyygqfzvnonukyegkbegioqbbatvdxtrmrwtmczvcaviyxa", 
        d = "yfzzzvlllbsggmqtuwjzsjwnxrhgwbzoyuwhdnvazzrkzbburfdifydwyogchhylwrgeubjgoecaalwvbgggonkzamvkliwqxduaylbbejqktzprtdcgkxumrkpkexcxkzubkukcnherxkbtvbiauskektmsubtvwbbcgvbmzcllywjvezigmylixwbviffevplfxdrxcezgowbwyvddbmkbenmzbbaspxgthuekbletopmuovdvtldtgpvyfmqfzwgrrktsubmsxtfhdkvcltvuvpbknxhgnnvujfjczaekdlrubnyfzfdgbfjhpiainddigppmerbcrovibmdedrtwvlmajhdgmeyunsmqvjkondfmuozivmeaphyvrqtnwgpijafejixpqssdywteuvkujhzutxxyhjdvzmcindkvdraalasvngwdzzpganobfcaxlicervbbmsqxezakkrrubyjorgmsoecvcjtndggdhxkbmdzrccabcjibzllzggalaqjyillefseihufiiqjiaauanpmcmtzgmmyldaajoltghkkrmovvpifhpixijtdyaakokcpwzdnplftmtxfkxxaecsdlhcgtjebmcjsycgqefcdaehwsfmmgmhdivdarhspqwlxojengkqvlxjtmhpfghjwgnilksebxpmrvjkqtvamdbyphschkayoppzgacoiujpbnfrqdfuelsdingktvhcnfoyfytoxwprcdybanfptsnadgntkuoosuxfjrypzgpiyhkbbimsyqsfuxzznbkcynhlulcbeeowzqsbkcwqpryhnwfgxknmcsitoagbxukemagdbippudljdcaoldplnkdomdtmsapzfkgktdfgsxtctvmlskobzfvvkjsiyzsmvdovnisyhlfmjwjajpakropiguhzfscwyoubplgarbgdglvrqzofvozbnnicqsjmxljvahzonveymmjbytdheliwthfeerhqxqbebedevtinnofiurembfjorikrzpxxbtjuxdctpiqumbpsdsyxpdgklmwxftzgurhbkrdufkdyfjtzweurgiuifrhobhzwktrxtpmhczfjeuwbefvuanxdbauttkyxvlbesznbhpkhkmthsgbreuthadujjxjkukigskkynnhouloutbrzjxxuwjfwovcllkavfmxoexmalnzoeqfcsfqvcjgxtvejlihwdokkhugpzqzdgsruhbigwxrqqkafyrdkwhihpunnivdmizhupwfblbamtyrrzjyfnzywfqolhkniytiqqelmaaanfaknrbhkbbgpugpgqdaouthexxmicfminhirvxfmxxxyloduaijcjkkgstrekeqjeeukyffzyxarvofccvruarnyvvxjygspulwnstvcdnaqsdgnatbxrvxsaeutyvpblkrhllvoavcnmtdihknoypoeypdsseqncwogvzhiqrkemepuvrvioerhpxyqgxbtzeftswjbvesjxsxpkackiwxczgrqnrwcbzvxgcekgtakyvomsnwntdkbavgaitmpnidojufnksuijlnevcroqbjmiwfsyduoewipfbanileazkophicyiknhpxyibdhsyhpuztsmwvyzusrnllxqduyofszkhrxnfxhxdhfogbfcjhpehhdfrykgfawwpgeholjukgvxhddmlphzxpizhoakeszvacwizybvqmyqnhhjifxssyijyrjhgtatgaldnqlxctrkxsoaiehjnswwshnrbgfajdkwtfxajcdulpowgcnpgmzpipbhgvdpecjwxymnpmdcacyhttrgbigyufftmwhtecxjdyuizvpldjcsqfffsoggmhbdfrsleivmnqulefbxalmflthidmxrfvdxsvbhfmwidjpnvlalgbfkxyswpbiettwztmizwpudtzvtbvabyklflhkebezjemdmzyqbcnmwgnzjenbnbuacojedhtmfbwycngunpylkqpyrszfnymadkrwqmlnxpqmzaoqqermgijsfndvvkggammioqffoatbkoovttfdgedemdsxpqmzedpvgryfivimzqzfkpcicybcbseoxmjfzsbkzwszzzlmjqtzmgdublxrtakwsbrtqpvbhtdwqgczccgszzxkphbfdtvrcsetizalokfblchaofubtexdjerwkzplbdzpitmxnrpnpuashoqcuwkgtopvgyzsikzwsxexocvrvsbfybslszijqowegikzmyyaeqahifujwcrgtndmesgscibhpuwtmyyqshsgtgrdrzixkhttyzqikjsktaignxvzfmjffcnms";

        // cin >> c >> d;
        Solution obj;
        if(obj.isAnagram(c, d)) cout << "YES" << endl;
        else cout << "NO" << endl;
 

}

// } Driver Code Ends